source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

link_with 'UIKitExtension_Example'

target 'UIKitExtension_Example', :exclusive => true do
  pod "UIKitExtension", :path => "../"
end

target 'UIKitExtension_Tests', :exclusive => true do
  pod "UIKitExtension", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
